{% set version = '2.2-10' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-coxme
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/coxme_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/coxme/coxme_{{ version }}.tar.gz
  sha256: e235e4711b14c0c0fcc2ca06038fbc81f2309fe0fb49fa0567adfb3c180ee48a

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-matrix >=1.0
    - r-bdsmatrix >=1.3
    - r-nlme
    - r-survival >=2.36.14
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-matrix >=1.0
    - r-bdsmatrix >=1.3
    - r-nlme
    - r-survival >=2.36.14

test:
  commands:
    - $R -e "library('coxme')"           # [not win]
    - "\"%R%\" -e \"library('coxme')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=coxme
  license: LGPL-2
  summary: Cox proportional hazards models containing Gaussian random effects, also known as
    frailty models.
  license_family: LGPL
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Title: Mixed Effects Cox Models
# Priority: optional
# Package: coxme
# Version: 2.2-10
# Depends: survival (>= 2.36.14), methods, bdsmatrix(>= 1.3)
# Imports: nlme, Matrix (>= 1.0)
# Suggests: mvtnorm, kinship2
# LinkingTo: bdsmatrix
# LazyData: Yes
# LazyLoad: Yes
# Authors@R: person(c("Terry", "M."), "Therneau", role=c("aut", "cre"), email="therneau@mayo.edu")
# Description: Cox proportional hazards models containing Gaussian random  effects, also known as frailty models.
# License: LGPL-2
# NeedsCompilation: yes
# Packaged: 2018-05-11 12:10:40 UTC; therneau
# Author: Terry M. Therneau [aut, cre]
# Maintainer: Terry M. Therneau <therneau@mayo.edu>
# Repository: CRAN
# Date/Publication: 2018-05-13 16:48:05 UTC
