{% set version = "2.2-19" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-coxme
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/coxme_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/coxme/coxme_{{ version }}.tar.gz
  sha256: b71bf8bbc0e2481c2413ef3448247767e0271d6b6c1ce0522b78076121752f86

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix >=1.0
    - r-bdsmatrix >=1.3
    - r-nlme
    - r-survival >=2.36.14
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-matrix >=1.0
    - r-bdsmatrix >=1.3
    - r-nlme
    - r-survival >=2.36.14

test:
  commands:
    - $R -e "library('coxme')"           # [not win]
    - "\"%R%\" -e \"library('coxme')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=coxme
  license: LGPL-2.0-only
  summary: This package fits Cox proportional hazards models containing both  fixed and random effects.  The random effects can have a general form, of which familial interactions (a "kinship" matrix) is a particular special case.  Note that the simplest case of a mixed effects Cox model, i.e. a single random  per-group
    intercept, is also called a "frailty" model.  The approach is based on Rippatti and Palgren, Biometrics 2002.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Title: Mixed Effects Cox Models
# Priority: optional
# Package: coxme
# Version: 2.2-14
# Depends: survival (>= 2.36.14), methods, bdsmatrix(>= 1.3), R(>= 2.10)
# Imports: nlme, Matrix (>= 1.0)
# Suggests: mvtnorm, kinship2
# LinkingTo: bdsmatrix
# LazyData: Yes
# LazyLoad: Yes
# Authors@R: person(c("Terry", "M."), "Therneau", role=c("aut", "cre"), email="therneau@mayo.edu")
# Description: This package fits Cox proportional hazards models containing both  fixed and random effects.  The random effects can have a general form, of which familial interactions (a "kinship" matrix) is a particular special case.  Note that the simplest case of a mixed effects Cox model, i.e. a single random  per-group intercept, is also called a "frailty" model.  The approach is based on Rippatti and Palgren, Biometrics 2002.
# License: LGPL-2
# NeedsCompilation: yes
# Packaged: 2019-07-03 17:31:43 UTC; therneau
# Author: Terry M. Therneau [aut, cre]
# Maintainer: Terry M. Therneau <therneau@mayo.edu>
# Repository: CRAN
# Date/Publication: 2019-07-04 05:10:05 UTC
