appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: NMePECtDs6iMWbhY8wVSCJE7/HlfRKZfL2tLpZSM9OAxxUZqxusCU3sRRFh++PsjZF57qFIjh1e9m174az95fz9euHI5XZ7d6fYCTi6vjMnMdB/6mwM1kMNvyejNebPUs9O9UC46EGFRH9sgekUmi8297nIWqHDPNVj60dwJDiRDocdxK3aLjo4p21SKQrE0oiTqsyIaGXP5BAJPdGmZR39s6MZMRgvdRa6RhDgnPV4vo/59ihsI2m+cOJ3VTHSNADMNwkOT5+wPqKF6hSPRoERtH7AcdvhgP/RoY+i373CdT92DUEgMBSwm0Ct9tOLjzOyNVI6z0LFxi6qlksjo/rlEAcsLQwbwTw/WHlN/eIDXwxpge+kUF0fUtkfLIbQXZbZLeb9haZu/HHhfW0V6nf4GWbIDxELfnRrVr7c4uWugN3p25pzjZsIq5MA8wMpBc9LA2O+H3R0V5zunbOqCYZXgFZbx+GFnEOO333dvcEfPcYMxinNZAU0OtEPZuiBOVRUj93tsKoLjNi73yK+3t5RY6eUWPX35JkDghXZT9J2lNY4o9ohc1+VuKSMkW8xYu/HvjtLSRj3plxXry/pJ/MfsTSvDu2MtQbdkPFr0UskSFckZxQeT2X8K+7pZZexD1p87pahgsOvOvYW7rRsleA9fX/ECiWstgNTp1GePIug=}
